buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.drakeet.drawer'
    compileSdk 36
    defaultConfig { minSdk 21 }
    sourceSets {
        main {
            java.srcDirs = ['src/java']
            manifest.srcFile 'src/AndroidManifest.xml'
        }
    }
}

dependencies {
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.core:core:1.16.0'
}