buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.topjohnwu.superuser.ipc'
    compileSdk 36
    defaultConfig { minSdk 21 }
    buildFeatures { aidl true }
    sourceSets {
        main {
            java.srcDirs = ['src/java']
            aidl.srcDirs = ['src/aidl']
            manifest.srcFile 'src/AndroidManifest.xml'
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    compileOnly files('../../../prebuild/android/libsu-core/materialfile-libsu-core.aar')
}