buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'moe.shizuku.server'
    compileSdk 36
    defaultConfig { minSdk 21 }
    sourceSets {
        main {
            java.srcDirs = ['src/java']
            aidl.srcDirs = ['src/aidl']
            manifest.srcFile 'src/AndroidManifest.xml'
        }
    }
    buildFeatures {
        aidl true
    }
}