buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.davemorrissey.labs.subscaleview'
    compileSdk 36
    defaultConfig { minSdk 21 }
    sourceSets {
        main {
            java.srcDirs = ['src/java']
            res.srcDirs = ['src/res']
            manifest.srcFile 'src/AndroidManifest.xml'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
}