buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.21'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'coil.video'
    compileSdk 36
    defaultConfig { minSdk 21 }
    sourceSets {
        main {
            java.srcDirs = ['src/java']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-Xjvm-default=all']
        apiVersion = '1.9'
        languageVersion = '1.9'
    }
}

dependencies {
    compileOnly files('../../../prebuild/android/coil-base/materialfile-coil-base.aar')
    implementation 'androidx.core:core-ktx:1.16.0'
    compileOnly files('../../../prebuild/android/okhttp/materialfile-okhttp.jar')
    compileOnly files('../../../prebuild/android/okio/materialfile-okio.jar')
}